baseurl = "https://whaleblog.github.io/"
title = "WhaleFall's Blog"
languageCode = "zh-cn"
defaultContentLanguage = "zh"
theme = "hello-friend-ng"
paginate = 10
paginatePath = "page"

publishDir = "docs" 

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # 主页副标题
  homeSubtitle = "Don't cry, I am just a fish"

  # 禁用“阅读其他文章”链接
  disableReadOtherPosts = false

  # 启用分享按钮
  enableSharingButtons = true

  # 禁用全局语言切换菜单（因为只支持中文）
  enableGlobalLanguageMenu = false

  # SEO 元数据
  description = "WhaleFall's Blog"
  # keywords = "博客, 技术, 生活"
  images = [""]

  # 显示阅读时间
  showReadingTime = true

  # 显示文章字数
  showWordCount = true

  # EnableSharingButtons = false

  # 自定义社交链接
  [[params.social]]
    name = "github"
    url = "https://github.com/WhaleFall-UESTC"

  [[params.social]]
    name = "email"
    url = "mailto:166845494@qq.com"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  # post = "posts"

[languages.zh]
  title = "WhaleFall's Blog"
  languageName = "中文"
  weight = 1
  copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  [languages.zh.params]
    readOtherPosts = "浏览其他文章" 
    [languages.zh.params.logo]
      logoText = "WhaleFall"
      logoHomeLink = "/"

# 导航菜单配置
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/posts"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about"
  weight = 2

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags"
  weight = 2
